version: '3.7'

services: 
    db:
        image: postgres:12.0-alpine
        volumes: 
            - postgres_data:/var/lib/postgresql/data/
        environment:
            POSTGRES_DB: postgres_db
            POSTGRES_USER: postgres_user
            POSTGRES_PASSWORD: postgres_pass
        ports: 
            - 5432:5432
volumes: 
    postgres_data:
